resources:
  - name: pipelines
    type: git
    source:
      uri: https://github.com/seadowg/pipelines.git
      branch: master

  - name: pws
    type: cf
    source:
      api:
      username:
      password:
      organization:
      space:
      skip_cert_check: false

jobs:
  - name: test
    plan:
      - get: pipelines
        trigger: true
      - task: test
        file: pipelines/pipelines/jvm-test-deploy-pws/tasks/test.yml

  - name: deploy
    plan:
      - get: pipelines
        trigger: true
        passed: [test]
      - task: package
        file: pipelines/pipelines/jvm-test-deploy-pws/tasks/package.yml
      - put: pws
        params:
          manifest: package/pipelines/pipelines/jvm-test-deploy-pws/app/manifest.yml
